version: '3.8'

services:
  movies-app:
    image: nandu90199/movies0:latest
    ports:
      - 71:80
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    tmpfs:
      - /tmp
    volumes:
      - /opt/logs/movies/:/var/logs/apache2
    read_only: true
    security_opt:
      - "no-new-privileges:true"

  train-app:
    image: nandu90199/train0:latest
    ports:
      - 72:80
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    tmpfs:
      - /tmp
    volumes:
      - /opt/logs/train/:/var/logs/apache2
    read_only: true
    security_opt:
      - "no-new-privileges:true"

  dth-app:
    image: nandu90199/dth0:latest
    ports:
      - 73:80
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    tmpfs:
      - /tmp
    volumes:
      - /opt/logs/dth/:/var/logs/apache2
    read_only: true
    security_opt:
      - "no-new-privileges:true"

  recharge-app:
    image: nandu90199/recharge0:latest
    ports:
      - 74:80
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    tmpfs:
      - /tmp
    volumes:
      - /opt/logs/recharge/:/var/logs/apache2
    read_only: true
    security_opt:
      - "no-new-privileges:true"

